# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# The MockKeystoneForwarder contract, that we will use for simulations, 
# on Ethereum Sepolia is located at: 
# https://sepolia.etherscan.io/address/0x15fc6ae953e024d975e77382eeec56a9101f9f88#code 
# forwarderAddress: "0x15fc6ae953e024d975e77382eeec56a9101f9f88"
